# Generated by Django 5.2.6 on 2025-10-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancerecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='compliancerecord',
            name='compliant_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compliancerecord',
            name='non_compliant_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compliancerecord',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
