# Generated by Django 5.2.6 on 2025-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_compliancerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('dates', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
