# Generated by Django 5.2.6 on 2025-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leads_notified',
            field=models.BooleanField(default=False),
        ),
    ]
